import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, FileText, RefreshCw } from 'lucide-react';
import type { Analysis, Evidence, Holding } from './lib/types';
import { clientName, dateLabel, money, percent, shortName } from './lib/format';
import { underlyingCompanies } from './lib/instruments';

export interface FundLookupState { status: 'loading' | 'ready' | 'unavailable'; message?: string; elapsedMs?: number }
export function FundGraph({ analysis, holding, onBack, onEvidence, lookup, onRefresh }: {
  analysis: Analysis; holding: Holding; onBack: () => void; onEvidence: (e: Evidence) => void;
  lookup?: FundLookupState; onRefresh?: (isin: string) => void;
}) {
  const [activeId, setActiveId] = useState('');
  const snapshot = holding.fundHoldings;
  const availableWeight = analysis.portfolios.length === 1 || (analysis.aum != null && analysis.aum > 0);
  const companies = underlyingCompanies(holding, availableWeight).slice(0, 10);
  const active = companies.find(c => c.id === activeId);
  const coverage = companies.reduce((n, c) => n + c.weight, 0);
  const sectorRows = holding.fundBreakdown && holding.fundBreakdown.total > 0 ? Object.entries(holding.fundBreakdown.sectors).map(([name, weight]) => ({ name, weight: weight / holding.fundBreakdown!.total })).sort((a, b) => b.weight - a.weight) : [];
  const isOlder = snapshot && Date.now() - Date.parse(snapshot.asOf) > 90 * 86400000;
  return <div className="fund-detail">
    <button className="text-button" onClick={onBack}><ArrowLeft size={16} />Back to customer overview</button>
    <div className="fund-heading"><div><span className="eyebrow">INSIDE THE FUND / ETF</span><h2>{holding.displayName}</h2><p>{holding.isin || 'ISIN not supplied'} · {holding.portfolio} · {money(holding.value, holding.currency)}</p></div><button className="button secondary" onClick={() => onEvidence(holding.evidence)}><FileText size={15} />Position source</button></div>
    <div className="fund-source-banner"><div><strong>{snapshot ? `Top ${companies.length} published holdings · ${percent(coverage)} of fund` : lookup?.status === 'loading' ? 'Fetching top holdings…' : 'Company holdings not available yet'}</strong><p>{snapshot ? `${snapshot.sourceName} · As of ${dateLabel(snapshot.asOf, true)}${isOlder ? ' · Older snapshot' : ''}` : 'The supplied case data contains sector and geographic exposure, but no underlying company names.'}</p></div>{holding.isin && onRefresh && <button className="button secondary" disabled={lookup?.status === 'loading'} onClick={() => onRefresh(holding.isin!)}><RefreshCw size={14} />{lookup?.status === 'loading' ? 'Fetching…' : snapshot ? 'Refresh holdings' : 'Fetch top holdings'}</button>}</div>
    {lookup?.status === 'unavailable' && <p className="fund-lookup-message" role="status">{snapshot ? 'Keeping the saved snapshot. ' : ''}{lookup.message} The customer brief remains available.</p>}
    {snapshot ? <>
      <div className="graph-layout fund-graph-layout"><div className="graph-canvas"><div className="graph-caption"><span className="live-dot" />Client → fund → underlying holdings</div><div className="graph-scroll"><svg viewBox="0 0 950 790" className="relationship-graph fund-relationship-graph" aria-label={`Top ${companies.length} holdings of ${holding.displayName}`}>
        <path d="M 220 395 L 290 395" className="overview-edge" /><text x="253" y="377" textAnchor="middle" className="edge-label">owns fund</text>
        {companies.map((c, i) => { const y = 65 + i * 70; return <g key={c.id}><path d={`M 490 395 C 565 395, 570 ${y}, 670 ${y}`} className={`overview-edge ${activeId === c.id ? 'selected' : ''}`} /><text x="625" y={y - 8} textAnchor="middle" className="edge-label">{percent(c.weight, 2)}</text><g role="button" tabIndex={0} aria-label={`${c.name}: ${percent(c.weight, 2)} of fund`} className={`graph-node company ${activeId === c.id ? 'active' : ''}`} transform={`translate(670,${y - 27})`} onClick={() => setActiveId(c.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setActiveId(c.id); } }}><rect width="245" height="54" rx="11" className="node-bg" /><text x="14" y="23" className="node-title">{shortName(c.name, 32)}</text><text x="14" y="42" className="node-value">{c.scopeWeight == null ? 'Scope weight unavailable' : `≈ ${percent(c.scopeWeight, 2)} of client scope`}</text></g></g>; })}
        <g className="graph-node client" transform="translate(20,352)"><rect width="200" height="86" rx="13" className="node-bg" /><text x="14" y="22" className="node-type">CUSTOMER</text><text x="14" y="46" className="node-title">{shortName(clientName(analysis.customer), 24)}</text><text x="14" y="68" className="node-value">{money(analysis.aum, analysis.currency)}</text></g>
        <g className="graph-node fund" transform="translate(290,352)"><rect width="200" height="86" rx="13" className="node-bg" /><text x="14" y="22" className="node-type">FUND / ETF</text><text x="14" y="45" className="node-title">{shortName(holding.displayName, 27)}</text><text x="14" y="68" className="node-value">{availableWeight ? `${percent(holding.weight)} of client scope` : 'Scope weight unavailable'}</text></g>
        <text x="790" y="755" textAnchor="middle" className="node-value">{percent(Math.max(0, 1 - coverage))} remaining fund weight · not expanded</text>
      </svg></div></div><aside className="graph-inspector"><span className="finding-tag insight"><span />{active ? 'INDIRECT EXPOSURE' : 'PUBLISHED TOP HOLDINGS'}</span><h3>{active?.name || 'See what sits inside.'}</h3>{active ? <><div className="inspector-value">{percent(active.weight, 2)} of the fund</div><dl className="graph-position-details"><div><dt>Estimated scope weight</dt><dd>{active.scopeWeight == null ? 'Unavailable' : `≈ ${percent(active.scopeWeight, 2)}`}</dd></div><div><dt>Estimated position value</dt><dd>≈ {money(active.estimatedValue, holding.currency)}</dd></div><div><dt>Holding source date</dt><dd>{dateLabel(snapshot.asOf, true)}</dd></div></dl><p>Fund position weight × published underlying weight. This combines the case position with an external dated snapshot; it is an indicative exposure, not a direct shareholding or a historical valuation.</p></> : <p>Select any underlying holding to see its published fund weight and the estimated exposure through this client’s fund position.</p>}
        <a className="button secondary wide" href={snapshot.sourceUrl} target="_blank" rel="noreferrer">Open holdings source<ArrowUpRight size={14} /></a><div className="graph-question"><span className="eyebrow">COVERAGE</span><p>Only the top {companies.length} published holdings are shown. The remaining {percent(Math.max(0, 1 - coverage))} can include other securities, cash and other positions. It has not been assigned to companies.</p></div></aside></div>
      <div className="fund-top-ten"><div className="panel-heading"><h3>Top {companies.length} holdings</h3><span className="subtle-badge">{dateLabel(snapshot.asOf, true)}</span></div><div className="fund-company-list">{companies.map((c, i) => <button key={c.id} onClick={() => setActiveId(c.id)} className={activeId === c.id ? 'active' : ''}><span>{String(i + 1).padStart(2, '0')}</span><strong>{c.name}</strong><b>{percent(c.weight, 2)}</b></button>)}</div></div>
    </> : <div className="fund-empty panel"><h3>{lookup?.status === 'loading' ? 'The graph will expand when the lookup finishes.' : 'No company names can be inferred from sector weights.'}</h3><p>Funds without a verified company list still show their supplied sector breakdown below. Some funds hold bonds or other assets rather than company shares.</p></div>}
    {!!sectorRows.length && <section className="panel fund-sectors"><div className="panel-heading"><h3>Sector exposure from the case dataset</h3><span className="subtle-badge">SEPARATE SOURCE</span></div><div className="fund-sector-list">{sectorRows.map(s => <div key={s.name}><span>{s.name}</span><i><b style={{ width: `${s.weight * 100}%` }} /></i><strong>{percent(s.weight)}</strong></div>)}</div><p className="microcopy">Sector weights are normalized within this fund. They are not company holdings and may use a different date from the external snapshot.</p></section>}
  </div>;
}
