import { NewsThumbnail } from './NewsThumbnail';
import { useState } from 'react';
import { ArrowUpRight, Network, RefreshCw, X } from 'lucide-react';
import type { useBriefing } from './useBriefing';
import type { Evidence } from './lib/types';
import { contextEvidence, type ContextItem } from './lib/briefing';
import { materialEvent, compareNews } from './lib/events';
import { dateLabel } from './lib/format';
import { RangeControl } from './PortfolioOverview';
export function rankedNews(items: ContextItem[]) { return [...items].sort(compareNews); }
export function MarketNewsPanel({ briefing, focus, onClear, onEvidence, onGraph }: { briefing: ReturnType<typeof useBriefing>; focus: {id:string;name:string}|null; onClear:()=>void; onEvidence:(e:Evidence)=>void; onGraph:(id:string)=>void }) {
  const [all,setAll]=useState(false),[researchError,setResearchError]=useState('');
  const items=rankedNews((briefing.context?.items || []).filter(i=>!focus || i.entityIds.includes(focus.id)));
  return <div className="ws-news-detail"><div className="ws-news-controls"><RangeControl value={briefing.newsRange} onChange={briefing.setNewsRange} label="News publication period"/><span>News published within {({'1D':'24 hours','7D':'7 days','1M':'30 days','1Y':'1 year'} as const)[briefing.newsRange]} of today</span><button className="ws-button" disabled={!!briefing.phase} onClick={()=>briefing.refresh()}><RefreshCw size={14}/>{briefing.phase?'Checking…':'Refresh'}</button></div>{focus && <button className="ws-filter-chip" onClick={onClear}>{focus.name}<X size={13}/></button>}
    <p className="ws-note">Current news is separate from the dated portfolio history. Headlines show possible relevance, not proven impact.</p><div className="ws-news-articles">{(all?items:items.slice(0,12)).map(item=><article key={item.id} className={item.kind==='news'?'ws-news-full':''}>{item.kind==='news' && <NewsThumbnail item={item}/>}<div><div className="ws-news-meta"><span>{item.kind==='house-view'?`${item.source} · ${item.provenance==='bank-approved'?'bank approval declared':'public research'}`:item.source}</span><time>{dateLabel(item.publishedAt,true)}</time></div>{materialEvent(item.title) && <span className="ws-event-label">{materialEvent(item.title)!.label}</span>}<h3><a href={item.url} target="_blank" rel="noreferrer">{item.title}<ArrowUpRight size={15}/></a></h3><p>{item.relevance}</p><div className="ws-inline-actions"><button onClick={()=>onEvidence(contextEvidence(item))}>Source details</button><button onClick={()=>onGraph(item.id)}><Network size={13}/>Trace exposure</button></div></div></article>)}</div>{!items.length && <div className="ws-empty">{briefing.phase?'Checking news for this exposure…':'No matching headlines returned for this period. This does not rule out a material event.'}</div>}{items.length>12 && <button className="ws-button" onClick={()=>setAll(!all)}>{all?'Show fewer':`Show all ${items.length} articles`}</button>}
    <details className="ws-disclosure ws-research-import"><summary>House views & research · {briefing.research.length} in library</summary><p>Upload dated research as JSON. Topics use company ISINs or exact exposure labels. Only matching views appear for this client. Bank approval is the uploader’s declaration.</p><label className="ws-button">Import research<input type="file" accept=".json,application/json" className="visually-hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('Research file must be under 1 MB.');briefing.importResearch(await file.text());setResearchError('');}catch(error){setResearchError(error instanceof Error?error.message:'Invalid research file');}e.target.value='';}}/></label> <a className="ws-link" href="/research-template.json" download>Download JSON format</a>{briefing.research.length>0 && <button className="ws-link" onClick={briefing.clearResearch}>Clear library</button>}{researchError && <p role="alert">{researchError}</p>}{briefing.research.map((r,i)=><p key={i}>{r.title} · {r.publishedAt} · {r.provenance}</p>)}</details>
    <details className="ws-disclosure"><summary>News coverage{briefing.context?` · ${briefing.context.checked}/${briefing.context.requested} searches complete`:''}</summary>{briefing.context?.warnings.map(w=><p key={w}>{w}</p>)}<p>At most two ranked headlines per exposure. Entity matches and event flags need adviser verification.</p></details>
  </div>;
}
