import { useMemo, useState } from 'react';
import { ArrowUpRight, BookmarkPlus, Network, RefreshCw, Search, X } from 'lucide-react';
import { WorldMap, sourceLocatedItems } from './WorldMap';
import { WorldRiskPanel } from './WorldRiskPanel';
import type { Analysis, Evidence } from './lib/types';
import { contextEvidence, newsTargets, type ContextItem, type MarketContext, type NewsTarget } from './lib/briefing';
import { portfolioExposures, type TimeRange } from './lib/portfolio';
import { scenarioEffect, worldViewItems, type WorldChokepoint } from './lib/world';
import { clientName, dateLabel, percent, money } from './lib/format';
import { materialEvent } from './lib/events';
import { lookThrough, mandate } from './lib/advisory';
import { eventQuestion, type EventDiscussion } from './lib/eventContext';
import './world.css';

const ranges:TimeRange[]=['1D','7D','1M','1Y'];
const clock=(date:string)=>new Date(date).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const classificationLabel=(target:NewsTarget)=>`Country: ${target.country||'unknown'} · Region: ${target.region||'unknown'} · Industry: ${target.industry||'unknown'}`;
const wordMatch=(title:string,name:string)=>{const phrase=name.replace(/\b(strait|canal)\b/gi,'').replace(/^\s*of\s+/i,'').trim();return phrase.length>3&&new RegExp(`\\b${phrase.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(title);};
export function WorldView({analysis,context,range,onRange,onEvidence,onGraph,onTrace,onAsk,onPin,onRefresh,busy}:{analysis:Analysis;context?:MarketContext;range:TimeRange;onRange:(range:TimeRange)=>void;onEvidence:(e:Evidence)=>void;onGraph:(id:string)=>void;onTrace:(item:ContextItem)=>void;onAsk:(selection:EventDiscussion)=>void;onPin:(item:ContextItem)=>void;onRefresh:()=>void;busy:boolean}) {
  const [eventId,setEventId]=useState(''),[query,setQuery]=useState(''),[universe,setUniverse]=useState<'company'|'macro'|'global'>('global'),[day,setDay]=useState('');
  const [worldMode,setWorldMode]=useState<'events'|'risk'>('events');
  const [layers,setLayers]=useState({news:true,shipping:true,disaster:true}),[exposurePreference,setExposurePreference]=useState<boolean>();
  const showExposure=exposurePreference??universe!=='global';
  const [chokepoint,setChokepoint]=useState<WorldChokepoint>();
  const [scenarioId,setScenarioId]=useState(''),[move,setMove]=useState(-10),[scenarioOpen,setScenarioOpen]=useState(false);
  const status=context?.world,targets=useMemo(()=>newsTargets(analysis),[analysis]);
  const allItems=useMemo(()=>worldViewItems(context,targets,{'1D':1,'7D':7,'1M':30,'1Y':365}[range]),[context,targets,range]);
  const hasLocatedEvents=useMemo(()=>sourceLocatedItems(allItems).some(item=>!!item.geo),[allItems]);
  const companyTargets=targets.filter(t=>!t.kind||t.kind==='company');
  const companyIds=new Set(companyTargets.map(t=>t.id));
  const hasCompany=(item:ContextItem)=>item.entityIds.some(id=>companyIds.has(id));
  const inUniverse=(item:ContextItem)=>universe==='global'||(universe==='company'?hasCompany(item):item.entityIds.length>0&&!hasCompany(item));
  const filtered=allItems.filter(i=>layers[i.layer||'news']&&inUniverse(i)&&(!query||`${i.title} ${i.summary||''} ${i.source}`.toLowerCase().includes(query.toLowerCase())));
  const days=[...new Set(filtered.map(i=>i.publishedAt.slice(0,10)))].sort().slice(-31);
  const activeDay=days.includes(day)?day:'';
  const visible=filtered.filter(i=>!activeDay||i.publishedAt.startsWith(activeDay));
  const event=visible.find(i=>i.id===eventId)||visible[0];
  const linked=event?targets.filter(t=>event.entityIds.includes(t.id)):[];
  const companies=companyTargets.filter(t=>t.weight!=null&&t.weight>0&&t.weight<=1);
  const eligible=companies.filter(t=>linked.some(l=>l.id===t.id));
  // A manual scenario belongs only to the event for which it was selected.
  const scenario=event?.id===eventId?companies.find(t=>t.id===scenarioId)||eligible[0]:eligible[0];
  const effect=scenarioEffect(scenario?.weight??null,move/100);
  const exposures=portfolioExposures(analysis,'country');
  const funds=analysis.holdings.filter(h=>h.instrumentType==='Investment fund');
  const partialFunds=funds.filter(h=>lookThrough(h).status==='partial');
  const missingFunds=funds.filter(h=>lookThrough(h).status==='unavailable');
  const clientNote=analysis.findings.find(f=>f.id==='customer-context');
  function select(item:ContextItem){setEventId(item.id);setChokepoint(undefined);setScenarioId('');setMove(-10);setScenarioOpen(false);}
  function discussion():EventDiscussion{return {item:event!,customerId:analysis.customer.ClientId,scope:analysis.scope,...(scenarioOpen&&scenario?{scenario:{companyId:scenario.id,move:move/100}}:{})};}
  const direct=linked.filter(t=>!t.kind||t.kind==='company');
  const macro=linked.filter(t=>t.kind&&t.kind!=='company');
  const relatedChokepointNews=chokepoint?allItems.filter(i=>wordMatch(i.title,chokepoint.name)).slice(0,4):[];
  return <section className="world-view" aria-label="Portfolio world intelligence">
    <div className="world-command"><div><span className="ws-kicker">WORLD INTELLIGENCE</span><h3>What’s happening. What it touches.</h3></div>{worldMode==='events'&&<><div className="world-range" aria-label="Event time window">{ranges.map(r=><button key={r} aria-pressed={range===r} onClick={()=>{onRange(r);setDay('');}}>{r}</button>)}</div><button className="ws-icon" aria-label="Refresh world intelligence" disabled={busy} onClick={onRefresh}><RefreshCw size={16}/></button></>}</div>
    <div className="world-client-scope"><strong>{clientName(analysis.customer)}</strong><span>{analysis.scope==='all'?'All supplied portfolios':analysis.portfolios[0]?.PortfolioNr}</span><span>{mandate(analysis).label}</span><span>{analysis.weightsAvailable?`${exposures.length} classified countries`:'Exposure weights unavailable'}</span></div>
    <p className="world-market-label">Global market benchmarks · independent of the selected client’s holdings</p>
    <div className="world-market-strip" aria-label="Global market observations">
      {(status?.quotes||[]).map(q=><a key={q.symbol} href={q.url} target="_blank" rel="noreferrer" title={`${q.source} · ${q.asOf?(q.changeBasis?dateLabel(q.asOf,true):clock(q.asOf)):'Observation time unavailable'} · ${q.changeBasis||'provider session change'}, not portfolio return`}><span>{q.name}<small>{q.unit||q.currency||''}</small></span><div><strong>{q.price.toLocaleString('en-US',{maximumFractionDigits:2})}</strong><b className={q.change==null?'':q.change>=0?'positive':'negative'}>{q.change==null?'—':`${q.change>=0?'+':''}${q.change.toFixed(2)}%`}</b></div><small>{q.asOf?(q.changeBasis?dateLabel(q.asOf,true):clock(q.asOf)):'As of unknown'} · {q.changeBasis||'session'}</small></a>)}
      {!status?.quotes?.length&&<p>{busy?'Loading dated market observations…':'Market observations unavailable.'}</p>}
    </div>
    <div className="world-mode-tabs" aria-label="World intelligence view"><button aria-pressed={worldMode==='events'} onClick={()=>setWorldMode('events')}>Events &amp; map</button><button aria-pressed={worldMode==='risk'} onClick={()=>setWorldMode('risk')}>Country instability (CII)</button></div>
    {worldMode==='risk'&&<WorldRiskPanel analysis={analysis}/>}
    <div className="world-events-mode" hidden={worldMode==='risk'}>
    <div className="world-filters"><div className="world-universe">{(['company','macro','global'] as const).map(view=><button key={view} aria-pressed={universe===view} onClick={()=>{setUniverse(view);setChokepoint(undefined);setDay('');}}>{view==='company'?'Held companies':view==='macro'?'Macro context':'Global'}<b>{allItems.filter(i=>view==='global'||(view==='company'?hasCompany(i):i.entityIds.length>0&&!hasCompany(i))).length}</b></button>)}</div><div className="world-layer-toggles">{(['news','shipping','disaster'] as const).map(layer=><label key={layer}><input type="checkbox" checked={layers[layer]} onChange={e=>{setLayers(l=>({...l,[layer]:e.target.checked}));setChokepoint(undefined);}}/><i className={`layer-${layer}`}/>{layer==='disaster'?'Natural events':layer==='shipping'?'Shipping':'News'}</label>)}<label><input type="checkbox" checked={showExposure} onChange={e=>setExposurePreference(e.target.checked)}/>Exposure</label></div></div>
    <div className="world-match-coverage"><p>{universe==='company'?'Company mentions matched to direct holdings or supplied fund constituents.':universe==='macro'?'Country, region and sector mentions without a held-company match. These are contextual links.':'All available source records, including events with no established client connection.'} {companyTargets.length} company targets in this portfolio scope{partialFunds.length?` · ${partialFunds.length} fund positions with partial look-through`: ''}{missingFunds.length?` · ${missingFunds.length} fund positions missing company look-through`: ''}.</p><details><summary>Holdings used for matching</summary>{companyTargets.length?<ul>{companyTargets.map(t=><li key={t.id}><button className="ws-link" onClick={()=>onGraph(t.id)}>{t.name}</button><span>{t.weight==null?'Weight unavailable':`${percent(t.weight,2)} covered exposure`} · {t.via}</span><span>{classificationLabel(t)}</span>{!!t.classificationEvidence?.length&&<button className="ws-link" onClick={()=>onEvidence({id:`metadata:${t.id}`,title:`${t.name} classifications`,type:'record',location:'Supplied security classifications',fields:t.classificationEvidence!.flatMap(e=>[...e.fields,{label:'Source',value:e.location}]),note:'Exact instrument classifications; geography is not an operating or revenue dependency. Missing or conflicting fields remain unknown.'})}>Classification sources ↗</button>}</li>)}</ul>:<p>No company targets are available from the supplied holdings. Macro context and Global remain available.</p>}<ul>{funds.map(h=><li key={h.id}><button className="ws-link" onClick={()=>onEvidence(h.evidence)}>{h.displayName}</button><span>{lookThrough(h).label}{h.fundHoldings?` · Holdings as of ${dateLabel(h.fundHoldings.asOf,true)} · ${h.fundHoldings.sourceName}`:''}</span>{h.fundHoldings&&<a href={h.fundHoldings.sourceUrl} target="_blank" rel="noreferrer">Constituent source ↗</a>}</li>)}</ul><p>Fund constituents may cover only part of a fund and have different observation dates. A lack of matching news does not establish a lack of risk.</p></details></div>
    <div className="world-layout">
      <div className={`world-main ${universe==='global'?'':'world-main--list-first'}`}>
        <WorldMap items={visible} selected={chokepoint?undefined:event} chokepoints={layers.shipping&&universe==='global'?status?.chokepoints||[]:[]} selectedChokepoint={chokepoint} exposures={exposures} showExposure={showExposure} loading={busy&&!status} onExploreLocations={universe!=='global'&&hasLocatedEvents?()=>{setUniverse('global');setLayers({news:true,shipping:true,disaster:true});setQuery('');setDay('');setChokepoint(undefined);}:undefined} onSelect={select} onChokepoint={c=>{setChokepoint(c);setScenarioOpen(false);setScenarioId('');}}/>
        <div className="world-timeline"><div><span>Event timeline · {range} · UTC dates</span><button onClick={()=>setDay('')} aria-pressed={!activeDay}>All dates</button>{activeDay&&<strong>{dateLabel(activeDay,true)}</strong>}</div><div className="world-timeline-bars">{days.map(d=>{const count=filtered.filter(i=>i.publishedAt.startsWith(d)).length,max=Math.max(...days.map(date=>filtered.filter(i=>i.publishedAt.startsWith(date)).length),1);return <button key={d} aria-label={`${d}: ${count} events`} aria-pressed={activeDay===d} title={`${d} · ${count} events`} onClick={()=>{setDay(activeDay===d?'':d);setChokepoint(undefined);}}><i style={{height:`${8+count/max*23}px`}}/><span>{d.slice(8)}</span></button>;})}</div><small>Last 31 dates with records shown; All dates includes the full selected window. Available sources are not a complete archive.</small></div>
        <div className="world-events"><header><strong>{visible.length} events {universe==='company'?'mentioning held companies':universe==='macro'?'with macro context':'in view'}</strong><label><Search size={13}/><input aria-label="Search world events" placeholder="Search events, places…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear event search" onClick={()=>setQuery('')}><X size={13}/></button>}</label></header><div className="world-event-list">{visible.slice(0,100).map(i=><button key={i.id} className={`world-event ${!chokepoint&&event?.id===i.id?'selected':''}`} onClick={()=>select(i)}><span className={`world-event-type layer-${i.layer||'news'}`}>{i.layer==='disaster'?'NATURAL EVENT':i.layer==='shipping'?'SHIPPING':hasCompany(i)?'HELD COMPANY MENTION':i.entityIds.length?'MACRO CONTEXT':'GLOBAL NEWS'}{materialEvent(i.title)?' · REVIEW':''}</span><strong>{i.title}</strong><small>{i.source} · {clock(i.publishedAt)}{hasCompany(i)&&i.exposureWeight!=null?` · ${percent(i.exposureWeight,2)} linked`:''}</small></button>)}{!visible.length&&<p className="world-empty">{busy?'Checking external sources…':'No events match these filters. Try Global, another layer or a wider time window.'}</p>}{visible.length>100&&<p className="world-empty">Showing 100 of {visible.length}. Use the timeline or search to narrow the list.</p>}</div></div>
      </div>
      <aside className="world-inspector">
        {chokepoint?<><span className="ws-kicker">SHIPPING INFRASTRUCTURE</span><h3>{chokepoint.name}</h3><span className="world-context-badge">{chokepoint.status==='reference'?'Reference location · live status unavailable':'Reported transit observations'}</span><p>{chokepoint.detail}</p><h4>Associated routes</h4><ul>{chokepoint.routes.map(r=><li key={r}>{r}</li>)}</ul><p className="world-caveat">Route names describe infrastructure. Company use of these routes is not supplied by the client dataset.</p><a className="ws-link" href={chokepoint.url} target="_blank" rel="noreferrer">Source methodology ↗</a><h4>Related reporting</h4>{relatedChokepointNews.length?relatedChokepointNews.map(i=><button className="world-related-story" key={i.id} onClick={()=>{setQuery('');setDay('');setUniverse('global');setLayers(l=>({...l,news:true}));select(i);}}>{i.title} ↗</button>):<p>No matching report in the available feed.</p>}</>:event?<>
          <span className="ws-kicker">SELECTED EVENT</span><h3>{event.title}</h3><p className="world-byline">{event.source} · {clock(event.publishedAt)}</p>{event.geo&&event.geo.basis!=='country-mention'&&<p className="world-caveat">{event.geo.basis==='event-location'?'Source-reported event location':'Source article location; event location unverified'}: {event.geo.label}</p>}
          <span className="world-context-badge">{direct.length?'Held company mention · impact unverified':linked.length?'Country / sector context':'Global context · no portfolio match'}</span>
          <div className="world-linked-list">{[{label:'Matched companies',targets:direct},{label:'Macro classification matches',targets:macro}].filter(group=>group.targets.length).map(group=><div key={group.label}><h4>{group.label}</h4>{group.targets.map(t=><button className="world-linked" key={t.id} onClick={()=>onGraph(t.id)}><span>{t.name}<small>{t.kind||'Company'} · {t.via}</small>{(!t.kind||t.kind==='company')&&<small>{classificationLabel(t)}</small>}</span><b title="Covered exposure; overlapping classifications must not be added">{t.weight==null?'—':percent(t.weight,2)}<ArrowUpRight size={12}/></b></button>)}</div>)}</div>
          <p className="world-next-question">{eventQuestion(analysis,event)}</p>
          <div className="world-actions"><button className="ws-button ws-button--primary" disabled={!linked.length} onClick={()=>onTrace(event)}><Network size={14}/>Trace to portfolio</button><button className="ws-button" onClick={()=>onAsk(discussion())}>Prepare event question<ArrowUpRight size={13}/></button><button className="ws-link" onClick={()=>onPin(event)}><BookmarkPlus size={13}/>Add to meeting brief</button></div>
          <p className="world-caveat">Linked weights are covered exposure; company and macro classifications can overlap and must not be added. Country classification does not establish revenue or supply-chain exposure.</p>
          {clientNote&&<details className="world-source-detail"><summary>Recorded client context</summary><p>{clientNote.body}</p><button className="ws-link" onClick={()=>onEvidence(clientNote.evidence[0])}>Client record ↗</button></details>}
          <details className="world-source-detail"><summary>What the source reports</summary>{event.summary?<p>{event.summary}</p>:<p>No article summary supplied. Open the original source.</p>}<button className="ws-link" onClick={()=>onEvidence(contextEvidence(event))}>Inspect evidence & original source ↗</button><p className="world-caveat">Publication dates are current-world context; they do not explain shifted historical portfolio changes.</p></details>
          {!!companies.length&&<details className="world-scenario" open={scenarioOpen} onToggle={e=>setScenarioOpen(e.currentTarget.open)}><summary>Explore a hypothetical company move</summary><label>Company<select aria-label="Scenario company exposure" value={scenario?.id||''} onChange={e=>{setEventId(event.id);setScenarioId(e.target.value);}}><option value="">Choose a company…</option>{companies.map(t=><option key={t.id} value={t.id}>{t.name} · {percent(t.weight!,2)}</option>)}</select></label>{scenario&&!eligible.some(t=>t.id===scenario.id)&&<p className="world-caveat">Independent scenario: {scenario.name}. No connection to this event is established.</p>}<label>Assumed price move<strong>{move>0?'+':''}{move}%</strong><input aria-label="Hypothetical company price move" type="range" min="-50" max="50" step="1" value={move} onChange={e=>setMove(Number(e.target.value))}/></label><output><b>{effect==null?'Select a company':`${effect>0?'+':''}${(effect*100).toFixed(2)} pp`}</b><span>{scenario?`${percent(scenario.weight!,2)} covered exposure × ${move}% assumed move`:'No automatic company choice for a macro event'}</span>{effect!=null&&analysis.aum!=null&&<small>{money(analysis.aum*effect,analysis.currency)}</small>}</output><p className="world-caveat">Hypothetical sensitivity, not a forecast. Other prices, holdings and FX held fixed. Fund look-through may be partial.</p></details>}
        </>:<><span className="ws-kicker">EXPLORE THE WORLD</span><h3>Select an event or a shipping chokepoint.</h3><p>Inspect what happened, its source and any supported connection to this client.</p></>}
      </aside>
    </div>
    <div className="world-search-coverage"><strong>Client news screening</strong><span>{context?`${context.checked}/${context.requested} searches checked · ${Math.max(0,context.requested-context.checked)} ${busy?'pending or unsuccessful':'not completed'}`:'Search coverage not available yet'}</span>{!!context?.warnings.length&&<details><summary>{context.warnings.length} source warning{context.warnings.length===1?'':'s'}</summary>{context.warnings.map(warning=><p key={warning}>{warning}</p>)}</details>}<p>Global feed records do not count as completed client searches. No matching headline does not establish absence of exposure or events.</p></div>
    <details className="world-source-status"><summary>Sources & coverage · {status?.layers?.filter(l=>l.state==='available').length||0} available layers{busy?' · refreshing':''}</summary><div className="world-coverage-grid"><div><strong>World Monitor news</strong><p>{status?.message||'Connecting news…'}</p><small>{status?.articles||0} world-feed articles received · {allItems.filter(hasCompany).length} company mentions · {allItems.filter(i=>i.entityIds.length&&!hasCompany(i)).length} macro-only records in the selected window</small></div>{status?.layers?.map(l=><div key={l.id}><strong>{l.label}<span>{l.state}</span></strong><p>{l.message}</p><a href={l.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a></div>)}</div><p>Retrieved {status?.retrievedAt?clock(status.retrievedAt):'—'}. Market quotes have their own observation times. A source returning no data does not establish that no event exists.</p></details>
    </div>
  </section>;
}
