import { useEffect, useMemo, useRef, useState } from 'react';
import { geoCentroid, geoDistance, geoGraticule10, geoNaturalEarth1, geoOrthographic, geoPath } from 'd3-geo';
import type { Feature, FeatureCollection, Geometry } from 'geojson';
import { ArrowUpRight, Globe2, Map as MapIcon, Minus, Network, Plus, RefreshCw, RotateCcw, Search, X } from 'lucide-react';
import type { Analysis, Evidence } from './lib/types';
import { contextEvidence, newsTargets, type ContextItem, type MarketContext } from './lib/briefing';
import { portfolioExposures, type TimeRange } from './lib/portfolio';
import { countryKey, entityCountries, itemCountries, scenarioEffect } from './lib/world';
import { dateLabel, percent, money } from './lib/format';
import { materialEvent } from './lib/events';
import './world.css';

type Country = Feature<Geometry,{name:string;iso:string}>;
const ranges:TimeRange[]=['1D','7D','1M','1Y'];
export function WorldView({analysis,context,range,onRange,onEvidence,onGraph,onNewsGraph,onAsk,onRefresh,busy}:{analysis:Analysis;context?:MarketContext;range:TimeRange;onRange:(range:TimeRange)=>void;onEvidence:(e:Evidence)=>void;onGraph:(id:string)=>void;onNewsGraph:(id:string)=>void;onAsk:(question:string)=>void;onRefresh:()=>void;busy:boolean}) {
  const [geometry,setGeometry]=useState<Country[]>([]),[mapError,setMapError]=useState(false);
  const [flat,setFlat]=useState(false),[rotation,setRotation]=useState<[number,number]>([-12,-24]),[zoom,setZoom]=useState(1);
  const [scenarioId,setScenarioId]=useState(''),[move,setMove]=useState(-10);
  const [country,setCountry]=useState(''),[eventId,setEventId]=useState(''),[query,setQuery]=useState('');
  const drag=useRef<{x:number;y:number;rotation:[number,number];moved:boolean;country:string|null}|null>(null);
  useEffect(()=>{const c=new AbortController();fetch('/geo/countries.json',{signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then((d:FeatureCollection<Geometry,{name:string;iso:string}>)=>setGeometry(d.features)).catch(()=>{if(!c.signal.aborted)setMapError(true);});return()=>c.abort();},[]);
  const exposures=useMemo(()=>portfolioExposures(analysis,'country'),[analysis]);
  const countries=useMemo(()=>entityCountries(analysis),[analysis]);
  const targets=useMemo(()=>newsTargets(analysis),[analysis]);
  const countryFeatures=useMemo(()=>new Map(geometry.map(f=>[countryKey(f.properties.name),f])),[geometry]);
  const mapped=exposures.filter(e=>countryFeatures.has(countryKey(e.name)));
  const mappedWeight=mapped.reduce((sum,e)=>sum+e.weight,0);
  const byCountry=new Map(exposures.map(e=>[countryKey(e.name),e]));
  const selected=byCountry.get(country);
  const items=useMemo(()=>{
    const now=Date.now(),days={'1D':1,'7D':7,'1M':30,'1Y':365}[range];
    return (context?.items||[]).filter(i=>i.kind==='news'&&!i.sample&&Date.parse(i.publishedAt)<=now&&Date.parse(i.publishedAt)>=now-days*86400000).sort((a,b)=>Number(!!materialEvent(b.title))-Number(!!materialEvent(a.title))||(b.exposureWeight||0)-(a.exposureWeight||0)||b.publishedAt.localeCompare(a.publishedAt));
  },[context,range]);
  const visible=items.filter(i=>!country||itemCountries(i,countries).includes(country));
  const event=visible.find(i=>i.id===eventId)||visible[0];
  const linked=event?targets.filter(t=>event.entityIds.includes(t.id)):[];
  const projection=useMemo(()=>flat?geoNaturalEarth1().translate([400,248]).scale(148*zoom):geoOrthographic().translate([400,248]).scale(214*zoom).rotate(rotation).clipAngle(90),[flat,zoom,rotation]);
  const path=geoPath(projection),graticule=geoGraticule10();
  const visiblePoint=(point:[number,number])=>flat||geoDistance(point,[-rotation[0],-rotation[1]])<Math.PI/2;
  function focus(name:string){const key=countryKey(name);setCountry(key);setEventId('');const f=countryFeatures.get(key);if(f){const p=geoCentroid(f);setRotation([-p[0],-p[1]]);}}
  function selectEvent(item:ContextItem){setEventId(item.id);if(item.geo)setRotation([-item.geo.coordinates[0],-item.geo.coordinates[1]]);}
  const status=context?.world;
  const companies=targets.filter(t=>(!t.kind||t.kind==='company')&&t.weight!=null&&t.weight>=0&&t.weight<=1);
  const scenario=companies.find(t=>t.id===scenarioId)||companies.find(t=>linked.some(l=>l.id===t.id))||companies[0];
  const effect=scenarioEffect(scenario?.weight??null,move/100);
  return <section className="world-view" aria-label="Portfolio world intelligence">
    <div className="world-command"><div><span className="ws-kicker">THE WORLD THROUGH THIS PORTFOLIO</span><h3>Exposure. Events. Connections.</h3></div><div className="world-range" aria-label="News time window">{ranges.map(r=><button key={r} aria-pressed={range===r} onClick={()=>onRange(r)}>{r}</button>)}</div><button className="ws-icon" aria-label="Refresh world and portfolio news" disabled={busy} onClick={onRefresh}><RefreshCw size={16}/></button></div>
    <div className="world-metrics"><div><strong>{analysis.weightsAvailable?percent(mappedWeight,1):'—'}</strong><span>mapped to countries</span></div><div><strong>{mapped.length}</strong><span>countries located</span></div><div><strong>{items.length}</strong><span>linked headlines · {range}</span></div><p>Country references and fund allocations.<br/>Revenue and supply chains are not inferred.</p></div>
    <div className="world-layout">
      <aside className="world-countries"><div className="world-list-label"><span className="ws-kicker">Portfolio geography</span><Search size={13}/></div><input aria-label="Find a portfolio country" placeholder="Find a country…" value={query} onChange={e=>setQuery(e.target.value)}/><button className={`world-country world-country-all ${!country?'selected':''}`} onClick={()=>{setCountry('');setEventId('');}}><span>All portfolio news</span><b>{items.length}</b></button>
        {exposures.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())).map(e=>{const key=countryKey(e.name),count=items.filter(i=>itemCountries(i,countries).includes(key)).length;return <button className={`world-country ${country===key?'selected':''}`} key={e.id} onClick={()=>focus(e.name)}><span>{e.name}<small>{count?`${count} linked headlines`:'No matching headlines'}{!countryFeatures.has(key)?' · not on map':''}</small></span><b>{percent(e.weight,1)}</b><i style={{width:`${Math.min(e.weight*100,100)}%`}}/></button>;})}
        {!exposures.length&&<p className="world-empty">{analysis.weightsAvailable?'Country-level exposure is not supplied.':'Select a portfolio with reliable weights to map exposure.'}</p>}
        <div className="world-coverage"><span className="ws-kicker">Outside the country map</span><strong>{analysis.weightsAvailable?percent(Math.max(0,1-mappedWeight),1):'—'}</strong><p>Regional allocations, cash, unclassified exposure and countries without a map shape.</p>{portfolioExposures(analysis,'region').filter(e=>!byCountry.has(countryKey(e.name))).slice(0,4).map(e=><button key={e.id} onClick={()=>onGraph(e.id)}>{e.name}<span>{percent(e.weight,1)} ↗</span></button>)}</div>
      </aside>
      <div className="world-stage"><div className="world-map-toolbar"><span><i/>{selected?selected.name:'GLOBAL PORTFOLIO LENS'}</span><div><button aria-label="Globe projection" aria-pressed={!flat} onClick={()=>{setFlat(false);setZoom(1);}}><Globe2 size={14}/>Globe</button><button aria-label="Flat map projection" aria-pressed={flat} onClick={()=>{setFlat(true);setZoom(1);}}><MapIcon size={14}/>Map</button></div></div>
        <svg className={`world-map ${flat?'is-flat':''}`} viewBox="0 0 800 500" role="img" aria-label="Interactive country exposure map. Select countries using the adjacent list; drag the globe to rotate."
          onPointerDown={e=>{if(flat)return;drag.current={x:e.clientX,y:e.clientY,rotation,moved:false,country:(e.target as Element).getAttribute('data-country')};e.currentTarget.setPointerCapture(e.pointerId);}}
          onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>4)d.moved=true;setRotation([d.rotation[0]+dx*.3/zoom,Math.max(-80,Math.min(80,d.rotation[1]-dy*.3/zoom))]);}}
          onPointerUp={e=>{const d=drag.current;if(!d?.moved){const key=d?.country;if(key)focus(key);}drag.current=null;}}
          onPointerCancel={()=>{drag.current=null;}}>
          <defs><radialGradient id="world-ocean"><stop offset="0%" stopColor="#182936"/><stop offset="100%" stopColor="#09131e"/></radialGradient><filter id="world-glow"><feGaussianBlur stdDeviation="3"/></filter></defs>
          <path d={path({type:'Sphere'})||''} className="world-sphere"/><path d={path(graticule)||''} className="world-grid"/>
          {geometry.map(f=>{const key=countryKey(f.properties.name),e=byCountry.get(key);return <path key={`${f.id}:${f.properties.name}`} d={path(f)||''} data-country={e?e.name:undefined} onClick={()=>{if(flat&&e)focus(e.name);}} className={`world-land ${e?'has-exposure':''} ${country===key?'is-selected':''}`} style={e?{fill:country===key?'#f4bd64':`rgba(205,148,63,${.24+Math.min(e.weight*2,0.55)})`}:undefined}><title>{f.properties.name}{e?` · ${percent(e.weight,1)} of portfolio`:' · no mapped exposure'}</title></path>;})}
          {mapped.map(e=>{const f=countryFeatures.get(countryKey(e.name))!,center=geoCentroid(f);if(!visiblePoint(center))return null;const p=projection(center);if(!p)return null;const count=items.filter(i=>itemCountries(i,countries).includes(countryKey(e.name))).length;return <g key={e.id} className="world-pin" onClick={()=>{if(flat)focus(e.name);}}><circle data-country={e.name} cx={p[0]} cy={p[1]} r={9+Math.sqrt(e.weight)*10} className="world-pin-glow" filter="url(#world-glow)"/><circle data-country={e.name} cx={p[0]} cy={p[1]} r={4+Math.sqrt(e.weight)*8}/><title>{e.name} · {percent(e.weight,1)} exposure · {count} linked headlines. Marker represents holdings geography.</title></g>;})}
          {event?.geo&&visiblePoint(event.geo.coordinates)&&(()=>{const p=projection(event.geo.coordinates)!;return <g className="world-event-pin"><circle cx={p[0]} cy={p[1]} r="11"/><circle cx={p[0]} cy={p[1]} r="3"/><title>Feed-supplied article location: {event.geo.label}</title></g>;})()}
        </svg>
        {mapError&&<p className="world-map-error" role="status">Map asset unavailable. Country exposure and news remain available in the lists.</p>}
        <div className="world-map-bottom"><div className="world-legend"><span><i/>Portfolio geography</span><span><i/>Article location, when supplied</span></div><div className="world-zoom"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(2,z+.2))}><Plus size={14}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.75,z-.2))}><Minus size={14}/></button><button aria-label="Reset globe" onClick={()=>{setRotation([-12,-24]);setZoom(1);setCountry('');}}><RotateCcw size={14}/></button></div></div>
        <div className="world-events"><header><span className="ws-kicker">{selected?`${selected.name} · linked news`:'Events to investigate'}</span><span>{visible.length} headlines{country&&<button aria-label="Show all portfolio news" onClick={()=>setCountry('')}><X size={12}/></button>}</span></header><div className="world-event-list">{visible.slice(0,24).map(i=><button key={i.id} className={`world-event ${event?.id===i.id?'selected':''}`} onClick={()=>selectEvent(i)}><span className={materialEvent(i.title)?'event-review':''}>{materialEvent(i.title)?'REVIEW · ':''}{dateLabel(i.publishedAt,true)}</span><strong>{i.title}</strong><small>{i.source}</small></button>)}{!visible.length&&<p className="world-empty">{busy?'Checking dated news sources…':'No matching headlines in this window. This does not establish that there are no relevant events.'}</p>}</div></div>
      </div>
      <aside className="world-inspector">{event?<><span className="ws-kicker">01 / WHAT HAPPENED</span><h3>{event.title}</h3><p className="world-byline">{event.source} · {dateLabel(event.publishedAt,true)}</p>{event.summary&&<p>{event.summary}</p>}<button className="ws-link" onClick={()=>onEvidence(contextEvidence(event))}>Open evidence & source<ArrowUpRight size={13}/></button>
        <div className="world-inspector-section"><span className="ws-kicker">02 / WHY IT IS LINKED</span>{linked.slice(0,5).map(t=><button className="world-linked" key={t.id} onClick={()=>onGraph(t.id)}><span>{t.name}<small>{t.kind||'Company'} · {t.via}</small></span><b>{t.weight==null?'—':percent(t.weight,1)}<ArrowUpRight size={12}/></b></button>)}<p className="world-caveat">Inferred news relevance. Weights show linked exposure, not a predicted loss; overlapping categories are not added together.</p></div>
        <div className="world-inspector-section"><span className="ws-kicker">03 / PREPARE THE CONVERSATION</span><p>Check the original report, then review the linked holdings against this client’s objectives and mandate.</p><button className="ws-button ws-button--primary" onClick={()=>onNewsGraph(event.id)}><Network size={14}/>Trace event to holdings</button><button className="ws-button" onClick={()=>onAsk(`How is this news relevant to this client and their holdings: ${event.title.slice(0,450)}? Distinguish verified facts from possible implications.`)}>Discuss with Compass<ArrowUpRight size={13}/></button></div>
      </>:selected?<><span className="ws-kicker">COUNTRY EXPOSURE</span><h3>{selected.name}</h3><strong className="world-country-weight">{percent(selected.weight,1)}</strong><p>Reported portfolio exposure via {selected.via.join(', ')}.</p><button className="ws-button ws-button--primary" onClick={()=>onGraph(selected.id)}><Network size={14}/>Trace to holdings</button><button className="ws-link" onClick={()=>selected.evidence[0]&&onEvidence(selected.evidence[0])}>Inspect allocation source<ArrowUpRight size={13}/></button><p className="world-caveat">Reference country and allocation data do not measure where a company earns revenue.</p></>:<><span className="ws-kicker">EXPLORE THE CONNECTION</span><h3>The world, through your client’s investments.</h3><p>Select a country to see its reported weight and linked news. Select a headline to trace it back to the portfolio.</p><p className="world-caveat">Current news is context for today’s conversation. It cannot explain historical movements in this date-shifted case dataset.</p></>}{companies.length>0&&<details className="world-scenario"><summary>Explore a hypothetical move</summary><label>Company exposure<select aria-label="Scenario company exposure" value={scenario?.id||''} onChange={e=>setScenarioId(e.target.value)}>{companies.map(t=><option key={t.id} value={t.id}>{t.name} · {t.via}</option>)}</select></label><label>Assumed price move<strong>{move>0?'+':''}{move}%</strong><input aria-label="Hypothetical company price move" type="range" min="-50" max="50" step="1" value={move} onChange={e=>setMove(Number(e.target.value))}/></label><output><b>{effect==null?'—':`${effect>0?'+':''}${(effect*100).toFixed(2)} pp`}</b><span>Mechanical portfolio value effect</span>{effect!=null&&analysis.aum!=null&&<small>{money(analysis.aum*effect,analysis.currency)}</small>}</output><p className="world-caveat">Hypothetical, not a forecast. {scenario?.weight!=null?percent(scenario.weight,2):'Unknown'} covered exposure × assumed price move. All other prices, holdings and exchange rates held constant. Fund look-through is partial; no knock-on effects are estimated.</p></details>}</aside>
    </div>
    <footer className="world-source-status"><span className={`world-status-dot ${status?.state==='complete'||status?.state==='partial'?'connected':''}`}/><strong>World Monitor</strong><span>{status?status.message:'Connecting the external digest…'}</span>{status?.generatedAt&&<time dateTime={status.generatedAt}>Digest {dateLabel(status.generatedAt,true)}</time>}<details><summary>Coverage</summary><p>{status?`${status.articles} dated feed articles screened; ${status.matched} matched to this portfolio. Retrieved ${status.retrievedAt}.`:'Feed results will appear after screening.'} Older time windows filter the available feed; a full news archive is not supplied. Mapped exposure excludes unlocated country records and regional allocations. Natural Earth map via world-atlas.</p></details></footer>
  </section>;
}
